### ISSUE TITLE
is the Thermostat Humidity Service broken?

### ISSUE THREAD

**Issue by Chrischi-** [andrei-tatar/nora-service#8]
no matter which value is submit the answer from Google Assistant is 0% Humidity.

**queryOnlyHumiditySetting**
```
Boolean. Optional. Defaults to false. Indicates if the device can only
be queried for state information and cannot be controlled. Sensors that can only 
report humidity should set this field to true. Avoid setting both commandOnlyHumiditySetting
and queryOnlyHumiditySetting to true.
```

do i need to set `queryOnlyHumiditySetting` to `true`? and how? which topic?

Is this a Google or NORA Problem?

**Comment by andrei-tatar** [comment]
Should be fixed now in the latest version 0.0.25

**Comment by Chrischi-** [comment]
I tried to register myself again to try this but got the following error when creating the token

```
https://node-red-google-home.herokuapp.com/

{"error":"Cannot read property 'replace' of undefined"}
```

**Comment by andrei-tatar** [comment]
@Chrischi- Try now. it should be fixed.

**Comment by Chrischi-** [comment]
Thank you, it works.

**Comment by Chrischi-** [comment]
I've tried setting the humidity and still get 0% in response.

and some error while trying to play with the following settings:
```
- Indicates if the device operates using one-way (checked) or two-way communication
- Required if the device supports query-only execution

"nora: sync error (invalid object for sync)"
```

**Comment by andrei-tatar** [comment]
Make sure you are sending a number between 0 and 100 for the `payload.humidity` property.

**Comment by Chrischi-** [comment]
I can set the payload and the google home app also answers with the right payload but the speech output is still 0% humidity.

```
This is the answer i get after setting a value via Google Home App.
mode: "heat"
setpoint: 20
setpointLow: 20
setpointHigh: 30
humidity: 47
```

@andrei-tatar 
i just found out that if i make the request in english, i get the right return. If I place the request in my national language, then I get 0%. This looks like a Google problem and not a NORA problem. Or can you still do something here?

**Comment by andrei-tatar** [comment]
@Chrischi- nope. can't do anything about it. I just pass the values to google.
